# Generated by Django 4.2 on 2024-02-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='direct/messages/audio/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='direct/messages/video/'),
        ),
    ]
