# Generated by Django 4.2.10 on 2024-03-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_alter_follow_followed_alter_follow_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='view_count',
        ),
    ]
