# Generated by Django 4.2 on 2024-02-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_follow_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='user_profiles/profile/pictures/'),
        ),
    ]
